# Generated by Django 2.1 on 2019-01-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('data_criacao', models.DateField()),
                ('importancia', models.IntegerField()),
                ('link', models.URLField()),
            ],
        ),
    ]
